-- MySQL Script generated by MySQL Workbench
-- Sun Feb  4 19:14:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema larabar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema larabar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `larabar` DEFAULT CHARACTER SET utf8 ;
USE `larabar` ;

-- -----------------------------------------------------
-- Table `larabar`.`suspended_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larabar`.`suspended_users` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `UID` INT(11) NULL DEFAULT NULL,
  `DURATION` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `larabar`.`user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larabar`.`user_profiles` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `UID` INT(11) NOT NULL,
  `BIO` VARCHAR(10000) NULL DEFAULT NULL,
  `IMGURL` VARCHAR(500) NULL DEFAULT NULL,
  `LOCATION` VARCHAR(100) NULL DEFAULT NULL,
  `EDUCATION` VARCHAR(1000) NULL DEFAULT NULL,
  `EMPLOYMENT_HISTORY` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `larabar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larabar`.`users` (
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `FIRSTNAME` VARCHAR(50) NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `ADMIN` TINYINT(4) NULL DEFAULT NULL,
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `AVATAR` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
